"""empty message

Revision ID: 2cd8ac1befe4
Revises: 
Create Date: 2018-08-08 20:20:56.696455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cd8ac1befe4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('migrate_version')
    op.drop_index('ix_book_genre_genre', table_name='book_genre')
    op.create_index(op.f('ix_book_genre_genre'), 'book_genre', ['genre'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_genre_genre'), table_name='book_genre')
    op.create_index('ix_book_genre_genre', 'book_genre', ['genre'], unique=1)
    op.create_table('migrate_version',
    sa.Column('repository_id', sa.VARCHAR(length=250), nullable=False),
    sa.Column('repository_path', sa.TEXT(), nullable=True),
    sa.Column('version', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('repository_id')
    )
    # ### end Alembic commands ###
