"""empty message

Revision ID: 95e5dc32eb88
Revises: 2cd8ac1befe4
Create Date: 2018-08-08 20:45:06.710990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95e5dc32eb88'
down_revision = '2cd8ac1befe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('lastname', sa.String(length=150), nullable=True))
    op.create_index(op.f('ix_author_lastname'), 'author', ['lastname'], unique=False)
    op.drop_index('ix_author_name', table_name='author')
    op.create_index(op.f('ix_author_name'), 'author', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_author_name'), table_name='author')
    op.create_index('ix_author_name', 'author', ['name'], unique=1)
    op.drop_index(op.f('ix_author_lastname'), table_name='author')
    op.drop_column('author', 'lastname')
    # ### end Alembic commands ###
